spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGHOST}:/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create




#spring.datasource.url=jdbc:
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create


#spring.datasource.username=postgres
#spring.datasource.password=
