spring:
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:23644/railway?user=postgres&password=fBtnhDRIEtsHHtleikzbAqvkBRZXeoQr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ou 'none', 'create', 'validate', dependendo da sua necessidade
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.show_sql: true


#url: jdbc:postgresql://${PGHOST}:${PGHOST}:/${PGDATABASE}

#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: create #validate | update | create | create-drop
#    properties:
#      hibernate:
#        format_sql: true


#spring.datasource.url=jdbc:
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create


#spring.datasource.username=postgres
#spring.datasource.password=
