spring.datasource.url=jdbc:postgresql://postgres:hURCBhPGmEbhQKxOPutTAcAxZXrwgmAC@shinkansen.proxy.rlwy.net:45774/railway
spring.datasource.username=postgres
spring.datasource.password=hURCBhPGmEbhQKxOPutTAcAxZXrwgmAC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create



#postgresql://postgres:hURCBhPGmEbhQKxOPutTAcAxZXrwgmAC@shinkansen.proxy.rlwy.net:45774/railway
#postgresql://postgres:hURCBhPGmEbhQKxOPutTAcAxZXrwgmAC@postgres.railway.internal:5432/railway
